import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout(
  { 
    children, 
    metaTitle 
  }: 
  { 
    children: React.ReactNode;
     metaTitle?: string }
  ) 
  {
  return (
    <>
      <Head>
        <title>{`Next.js App - ${metaTitle || ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>Header</div>
        <div>{children}</div>
        <div>Footer</div>
      </div>
    </>
  );
}
