import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout(
  { 
    children, 
    metaTitle 
  }: 
  { 
    children: React.ReactNode;
     metaTitle?: string }
  ) 
  {
  return (
    <>
      <Head>
        <title>{`Next.js App - ${metaTitle || ''}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* cara akses style global */}
        {/* style global ini di render sama misal header = header */}
        <div className="header">Header</div>
        {/* cara akses style module */}
        {/* cara akses id namun tidak di sarankan */}
        <div id={styles.main}>{children}</div>
        {/* cara akses style module */}
        {/* style module ini di render sama unique footer = akan du generate berbeda namanya */}
        <div className={styles.footer}>Footer</div>

      </div>
    </>
  );
}
